# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: summary_message.proto for package 'summarymessage'

require 'grpc'
require_relative 'summary_message_pb'

module Summarymessage
  module SummaryMessageManager
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'summarymessage.SummaryMessageManager'

      # RPC method to get summary message
      rpc :GetSummary, ::Summarymessage::AlertMessageRequest, ::Summarymessage::SummaryResponse
    end

    Stub = Service.rpc_stub_class
  end
end
